src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    const QUALITY_MP3_128 = 'MP3_128';
    const QUALITY_MP3_192 = 'MP3_192';
    const QUALITY_MP3_256 = 'MP3_256';
    const QUALITY_MP3_320 = 'MP3_320';
    const QUALITY_FLAC    = 'FLAC';
    const DEFAULT_QUALITY = self::QUALITY_MP3_320;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    protected $id;

    /**
     * @ORM\Column(length=50)
     * @var string
     */
    protected $quality = self::DEFAULT_QUALITY;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $zip_tracks = false;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    protected $zip_add_cover = false;

    /**
     * @return bool
     */
    public function isWhiteListed()
    {
        return $this->hasRole('ROLE_WHITE_LISTED') or $this->hasRole('ROLE_ADMIN');
    }

    /**
     * @return array
     */
    public static function getQualities()
    {
        return [
            'user.quality.mp3.128' => self::QUALITY_MP3_128,
            'user.quality.mp3.192' => self::QUALITY_MP3_192,
            'user.quality.mp3.256' => self::QUALITY_MP3_256,
            'user.quality.mp3.320' => self::QUALITY_MP3_320,
            'user.quality.flac'    => self::QUALITY_FLAC,
        ];
    }

    /**
     * @param User $user
     * @return string
     */
    public static function getUserQuality(User $user = null)
    {
        return ($user === null ? self::DEFAULT_QUALITY : $user->getQuality());
    }

    /**
     * @param User $user
     * @return bool
     */
    public static function getUserZipTracks(User $user = null)
    {
        return ($user === null ? false : $user->getZipTracks());
    }

    /**
     * @param User $user
     * @return bool
     */
    public static function getUserCover(User $user = null)
    {
        return ($user === null ? false : $user->getZipAddCover());
    }

    /**
     * @return string
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * @return string
     */
    public function getQualityTransKey()
    {
        return array_keys(self::getQualities(), $this->getQuality())[0];
    }

    /**
     * @param string $quality
     */
    public function setQuality($quality)
    {
        $this->quality = $quality;
    }


    /**
     * @return bool
     */
    public function getZipTracks()
    {
        return $this->zip_tracks;
    }

    /**
     * @param bool $zip_tracks
     */
    public function setZipTracks($zip_tracks)
    {
        $this->zip_tracks = $zip_tracks;
    }

    /**
     * @return bool
     */
    public function getZipAddCover()
    {
        return $this->zip_add_cover;
    }

    /**
     * @param bool $zip_add_cover
     */
    public function setZipAddCover($zip_add_cover)
    {
        $this->zip_add_cover = $zip_add_cover;
    }
}

src/AppBundle/Form/UserType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->remove('current_password')
            ->add('enabled')
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'ROLE_USER' => 'ROLE_USER',
                    'ROLE_WHITE_LISTED' => 'ROLE_WHITE_LISTED',
                    'ROLE_ADMIN' => 'ROLE_ADMIN',
                    'ROLE_SUPER_ADMIN' => 'ROLE_SUPER_ADMIN',
                ],
                'multiple' => true,
             ])
            ->add('quality', ChoiceType::class, [
                'choices' => User::getQualities(),
            ])
            ->add('zip_tracks')
            ->add('zip_add_cover')
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\ProfileFormType';
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_user';
    }
}

src/AppBundle/Resources/views/Admin/user/edit.html.twig
{% extends "@App/Admin/layout.html.twig" %}
{% form_theme edit_form ':Form:semantic-ui-form-theme.html.twig' %}

{% block title %}
    {{ parent() }}
    - User edit
{% endblock %}

{% block content %}
    <div class="ui grid">
        <div class="ui row">
            <h1>User edit</h1>
        </div>
        <div class="ui row">
            <div class="sixteen wide column">
                {{ form_start(edit_form) }}
                {{ form_widget(edit_form) }}
                <input class="ui primary button" type="submit" value="Edit" />
                {{ form_end(edit_form) }}
            </div>
        </div>
        <div class="ui row">
            {{ form_start(delete_form) }}
            <div class="ui buttons">
                <a class="ui button" href="{{ path('admin_user_index') }}">
                    Back to the list
                </a>
                <button class="ui negative button" data-requires-confirmation>
                    <i class="minus icon"></i>
                    Delete
                </button>
            </div>
            {{ form_end(delete_form) }}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/user/index.html.twig
{% extends "@App/Admin/layout.html.twig" %}
{% import '@App/Macro/labels.html.twig' as labels %}

{% block title %}
    {{ parent() }}
    - Users management
{% endblock %}

{% block content %}
    <h2>Users management</h2>
    <table class="ui celled table">
        <thead>
        <tr>
            <th>{{ knp_pagination_sortable(pagination, 'Id', 'u.id') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Username', 'u.usernameCanonical') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Email', 'u.emailCanonical') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Enabled', 'u.enabled') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'Last Login', 'u.lastLogin') }}</th>
            <th>Roles</th>
            <th>White Listed</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in pagination %}
            <tr {% if loop.index is odd %}class="color"{% endif %}>
                <td>
                    <a href="{{ path('admin_user_show', { 'id': user.id }) }}">
                        {{ user.id }}
                    </a>
                </td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ labels.status(user.enabled) }}</td>
                <td>{{ user.lastLogin ? user.lastLogin|date('d-M-Y G:i:s') : 'Never' }}</td>
                <td>{{ user.roles|join(', ') }}</td>
                <td>{{ labels.yesNo(user.isWhiteListed) }}</td>
                <td>
                    <div class="ui mini buttons">
                        <a href="{{ path('admin_user_edit', { 'id': user.id }) }}" class="ui button">
                            <i class="pencil icon"></i>
                            Edit
                        </a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/user/show.html.twig
{% extends "@App/Admin/layout.html.twig" %}
{% import '@App/Macro/labels.html.twig' as labels %}

{% block title %}
    {{ parent() }}
    - User view
{% endblock %}

{% block content %}
    <table class="ui celled table">
        <tbody>
            <tr>
                <td>Id</td>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <td>Username</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>
                    <a href="mailto:{{ user.email }}">
                        {{ user.email }}
                    </a>
                </td>
            </tr>
            <tr>
                <td>Enabled</td>
                <td>{{ labels.status(user.enabled) }}</td>
            </tr>
            <tr>
                <td>Last Login</td>
                <td>{{ user.lastLogin ? user.lastLogin|date('d-M-Y G:i:s') : 'Never' }}</td>
            </tr>
            <tr>
                <td>Roles</td>
                <td>{{ user.roles|join(', ') }}</td>
            </tr>
            <tr>
                <td>White Listed</td>
                <td>{{ labels.yesNo(user.isWhiteListed) }}</td>
            </tr>
            <tr>
                <td>Quality</td>
                <td>{{ user.qualityTransKey|trans }}</td>
            </tr>
        </tbody>
    </table>

    {{ form_start(delete_form) }}
    <div class="ui buttons">
        <a class="ui button" href="{{ path('admin_user_index') }}">
            Back to the list
        </a>
        <a class="ui primary button" href="{{ path('admin_user_edit', { 'id': user.id }) }}">
            <i class="pencil icon"></i>
            Edit
        </a>
        <button class="ui negative button" data-requires-confirmation>
            <i class="minus icon"></i>
            Delete
        </button>
    </div>
    {{ form_end(delete_form) }}

{% endblock %}